version: "3.8"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/todoDB
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]  
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
